travis:
  secure:
    BINSTAR_TOKEN: LK0oDkbRzd5SGJ7ZcFm5YpC1zD/iQ+bJEM7u8ZIp4uBnj2PJAcnRhC+gsn1BZra0vypxjO0ZIpjXyPNSZfPTOLf+cu5QojPzYPoXEiBnxYWE/Od3xRF64UaXWIKxF/M3ekpSfxO9SeTJ+DO331ddL8RfiPiQsw4w1+kemC5++MQLaP47FtS1HGnDT0/3m9j39QDImQg09DX66UGRFi48TD+ZQX7oA5w9UUe8Ej6AxEydz8iuKRK+dhIHLd/YCwwgDSkW+EjoSlNP8L+sjkRaYqU+fCoKUsnEtTXJn1h7FUwzHPzG/lKSm2vi+Ikg6rp/b4gPeFEMjDmQtGORlL+CPOCz6PXm+1eW8oJkHDueTJzkgsd/OEkejh8YoaEB5GeWpVD47y6MHFjPZprWuCre3hJq4r+gWGC8YBaoPU2SrPwc62gtikLuypZ58F3hjUJ4XpHNNGLyww7xH30DbqUU2sv2xZzTpzbV3T0wznzXUXzHqs9vCY4mQyqLuZaRMsix+4dBpf8TQXHXsM6B45l+sBQHR/2wwO577mklU3kN8ajBUzu52o50LUW1qruNEiKiv60HjkqF/o0eTnVGbliU8POgwANQ0mu2JoDtrIndaeEVwRXQK3SSH2c9Syr15HEfSB2mc3Lr5Bck9iaLKyGH/uL3GRcjQIXn+FHVtS+oIPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
